# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=256)),
                ('health', models.IntegerField(default=0)),
                ('player_regularity', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('no_malus', models.IntegerField(default=0)),
                ('advice', models.IntegerField(default=0)),
                ('my_custom_value', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=256)),
                ('sold', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
